runnerConfig:
  users: 10
  durationSeconds: 60
  thinkTimeMillis: 3000
  personas:
    - className: 'com.bolour.boardgame.benchmark.PlayerPersona'
      weight: 100
gameServerUrl: 'http://localhost:6587'
gameEndProbability: 0.1
