runnerConfig:
  users: 75
  durationSeconds: 50
  thinkTimeMillis: 100
  personas:
    - className: 'com.bolour.boardgame.benchmark.PlayerPersona'
      weight: 100
gameServerUrl: 'http://localhost:6587'
gameEndProbability: 0.1
