
#
# Install the eagerwords haskell server.
#

FROM ubuntu:bionic

RUN apt-get update \
  && apt-get install -y apt-utils wget curl zip unzip sudo

ENV PACKAGE_DIR=/opt/data/eagerwords/package

ENV WORKSPACE /home/me/dev/eagerwords
RUN mkdir -p $WORKSPACE \
  && mkdir $WORKSPACE/database \
  && chmod 777 $WORKSPACE/database

WORKDIR $WORKSPACE
ENV PATH $PATH:.

RUN tar -xf $PACKAGE_DIR/eagerwords-haskell.tar bin/install.sh && bin/install.sh

# TODO. Get config from config directory.
# TODO. Use variable for entry point parameters if possible.
ENTRYPOINT ["/usr/local/eagerwords/bin/eagerwords-server", "config.yml"]

