
ARG BASE=azadbolour/nodejs:13
ARG PROJECT=eagerwords.com

FROM $BASE

ENV WORKSPACE /home/me/dev/
RUN mkdir -p $WORKSPACE/${PROJECT} \
  && echo `pwd`&& echo $PATH && whoami

# The source tree will have been cloned by the script that invokes the build.
COPY ${PROJECT} $WORKSPACE/${PROJECT}

# Get the dependencies.
RUN cd $WORKSPACE/${PROJECT}/eagerwords-web && npm install && npm audit fix

WORKDIR $WORKSPACE/${PROJECT}/eagerwords-web

ENTRYPOINT [".build.sh"]
